homework_40/eventmanager/mainapp/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "mainapp"

urlpatterns = [
    path("", views.index, name="home_page"),
    path("event_details/<int:id>/", views.event_details, name="event_details"),
    path("add_event/", views.add_event, name="add_event"),
    path("delete_event/<int:id>/", views.delete_event, name="delete_event"),
    path("add_attendee_to_event/<int:id>/", views.add_attendee, name="add_attendee"),
    path("delete_attendee/<int:id>/", views.delete_attendee, name="delete_attendee"),
]

admin.site.index_title = "My Site Administration"
admin.site.site_header = "My Site Administration"

homework_40/eventmanager/mainapp/models.py
from django.db import models

class Category(models.Model):

    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


    class Meta:
        db_table = "category"
        verbose_name_plural = "category"


class Event(models.Model):

    title = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    date = models.DateField()
    location = models.CharField(max_length=50)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "event"
        verbose_name_plural = "event"


class Attendee(models.Model):

    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    event = models.ForeignKey(Event, related_name='attendees', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        db_table = "attendee"
        verbose_name_plural = "attendee"

homework_40/eventmanager/mainapp/forms.py
from django import forms
from .models import Attendee, Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'location', 'category']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control mt-2', 'placeholder': 'Please Enter The Title'}),
            'description': forms.Textarea(attrs={'class': 'form-control mt-2', 'placeholder': 'Please Enter The Description'}),
            'date': forms.DateInput(attrs={'class': 'form-control mt-2', 'type': 'date'}),
            'location': forms.TextInput(attrs={'class': 'form-control mt-2', 'placeholder': 'Please Enter The Location'}),
        }

class AttendeeForm(forms.ModelForm):
    class Meta:
        model = Attendee
        fields = ["name", "email"]
    
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control mt-2", "placeholder": "Enter name"}),
            "email": forms.EmailInput(attrs={"class": "form-control mt-2", "placeholder": "Enter email"})
        }

homework_40/eventmanager/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event, Attendee
from .forms import AttendeeForm, EventForm
from django.db.models import Q

def index(request):
    
    query = request.GET.get("query")
    
    if query:
        events = Event.objects.filter(Q(title__icontains=query) | Q(location__icontains=query))
    else:
        events = Event.objects.all()
    
    context = {"events": events}
    
    return render(request, "mainapp/index.html", context)

def event_details(request, id):

    try:
        event_info = Event.objects.get(pk=id)
    except:
        event_info = None
        attendees = None
    else:
        attendees = event_info.attendees.all()
        
    context = {"event": event_info, 'attendees': attendees}

    return render(request, "mainapp/event_details.html", context)

def add_event(request):
    
    if request.method == "POST":
        form = EventForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect("mainapp:home_page")
    else:
        form = EventForm()
        return render(request, "mainapp/add_event.html", {"form": form})

def delete_event(request, id):
    
    try:
        event_to_delete = Event.objects.get(pk=id)
        event_to_delete.delete()
    except:
        event_to_delete = None
    
    return redirect("mainapp:home_page")

def add_attendee(request, id):
    
    event = get_object_or_404(Event, pk=id)
    
    if request.method == "POST":
        form = AttendeeForm(request.POST)

        if form.is_valid():
            attendee = form.save(commit=False)
            attendee.event = event
            attendee.save()
            return redirect("mainapp:event_details", event.id)
    else:
        form = AttendeeForm()
        return render(request, "mainapp/add_attendee.html", {"form": form, "event": event})
        
def delete_attendee(request, id):

    try:
        attendee_to_delete = Attendee.objects.get(pk=id)
        event = attendee_to_delete.event_id
        attendee_to_delete.delete()
    except:
        attendee_to_delete = None
        event = None

    if event:
        return redirect("mainapp:event_details", event)
    else:
        return redirect("mainapp:home_page")

homework_40/eventmanager/mainapp/templates/mainapp/add_event.html
{% extends 'base.html' %}

{% block title %} Add Event {% endblock %}

{% block body %}

    <div class="container">
        <h3 class="mt-3 mb-3">Adding New Event</h3>

        <form method="post" style="width: 500px;">
            
            {% csrf_token %}
            {{ form.as_p }}
    
            <div class="d-flex justify-content-between mb-5">
                <button type="submit" class="btn btn-success">Add Event</button>
                <a href="{% url 'mainapp:home_page' %}" class="btn btn-primary ">Home Page</a>
            </div>
        </form>
    </div>

{% endblock %}

homework_40/eventmanager/mainapp/templates/mainapp/event_details.html
{% extends 'base.html' %}

{% block title %} Event Details {% endblock %}

{% block body %}

<div class="container">

    {% if event %}
    <h5 style="margin-top: 15px;">Event "{{event.title}}" </h5>
    <p>{{event.description}}</p>
    <h6>Will be held on {{ event.date }} <span style="font-weight: 300;">in</span> <a class="text-decoration-none"
            href="#">{{ event.location }}</a>
    </h6>
    <a href="{% url 'mainapp:add_attendee' event.id %}" class="btn btn-success mt-5">Add Attendee</a>
    <h4 style="margin-top: 30px;">Attendees: {{ attendees|length }}</h4>
    <ol class="list-group">
        {% for attendee in attendees %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ forloop.counter }}. {{ attendee }}
            <a href="{% url 'mainapp:delete_attendee' attendee.id %}" class="btn btn-danger"
                onclick="return confirm('Are you sure you want to delete attendee?');">Delete Attendee</a>
        </li>
        {% endfor %}
    </ol>
    <div class="d-flex justify-content-between mt-5 mb-5">
        <a href="{% url 'mainapp:home_page' %}" class="btn btn-primary ">Home Page</a>
        <a href="{% url 'mainapp:delete_event' event.id %}" class="btn btn-danger"
            onclick="return confirm('Are you sure you want to delete event?');">Delete Event</a>
    </div>
    {% else %}
        <h1>Event Does Not Exists!</h1>
    {% endif %}

</div>

{% endblock %}

homework_40/eventmanager/mainapp/templates/mainapp/index.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}

{% block body %}

<div class="container">

  <h1 class="mb-5 mt-3">Upcoming Events...</h1>
  <a href="{% url 'mainapp:add_event' %}" class="btn btn-success mb-4">Add Event</a>


  <div class="row mt-3">
    {% for event in events %}

    <div class="col-md-4 mb-4">
      <div class="card" style="width: 18rem">
        <img
          src="https://images.squarespace-cdn.com/content/v1/5dfc6153e5cf6f15c4b4c6a0/1579243089356-VBXN7YMWWYOZQ1EDAJ62/metallica.jpeg"
          class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">{{event.title}}</h5>
          <p class="card-text" style="height: 180px">
            {{event.description|slice:":200"}}...
            <a href="{% url 'mainapp:event_details' event.id %}">Continue Reading</a>
          </p>
          <p class="card-text"><strong>Date:</strong> {{event.date}}</p>
          <p class="card-text"><strong>Location:</strong> <a class="text-decoration-none" href="#">{{event.location}}</a> </p>

          <p class="card-text">
            <strong> Category: </strong>

            {% for category in event.category.all %}
            <span class="badge text-bg-secondary"> {{ category.name }} </span>
            {% endfor %}
          </p>

          <a href="{% url 'mainapp:event_details' event.id %}" class="btn btn-primary"
            style="width: 100%; margin-bottom: 10px;">Go To {{event.title}} </a>
          <div class="d-flex justify-content-between">
            <a href="{% url 'mainapp:delete_event' event.id %}" class="btn btn-danger"
              onclick="return confirm('Are you sure you want to delete event?');">Delete Event</a>
            <a href="{% url 'mainapp:add_attendee' event.id %}" class="btn btn-success ">Add Attendee</a>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>

{% endblock %}